nomad: configure network interface if needed

diff --git a/bin/minipot-init b/bin/minipot-init
--- a/bin/minipot-init
+++ b/bin/minipot-init
@@ -15,6 +15,20 @@ _inject_ip()
 	sysrc consul_args="-advertise $ip"
 }
 
+# $1 the IP address
+_find_netif()
+{
+	local ifs ip
+	ip="$1"
+	ifs="$(ifconfig | grep '^[a-z]' | cut -f 1 -d ":" | tr '\n' ' ')"
+	for netif in $ifs ; do
+		if ifconfig "$netif" | grep -q -F " $ip " ; then
+			echo $netif
+			return
+		fi
+	done
+}
+
 while getopts :i:h arg; do
 	case $arg in
 		h)
@@ -23,6 +37,11 @@ while getopts :i:h arg; do
 			;;
 		i)
 			ip="$OPTARG"
+			netif="$( _find_netif "$ip" )"
+			if [ -z "$netif" ]; then
+				echo "$ip is not bound to any interface - aborting"
+				exit 1
+			fi
 			;;
 		?)
 			print_syntax
@@ -35,14 +54,18 @@ if ! grep -c "^kern.racct.enable=1" /boot/loader.conf ; then
 	echo kern.racct.enable=1 >> /boot/loader.conf
 fi
 
-if [ ! -e /etc/pf.conf.potbkp ]; then
+if [ ! -e /etc/pf.conf.potbkp ] && [ -e /etc/pf.conf ]; then
 	cp /etc/pf.conf /etc/pf.conf.potbkp
-	pot init
 fi
+pot init
 
 sysrc nomad_user="root"
 sysrc nomad_env="PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin"
-sysrc nomad_args="-config=/usr/local/etc/nomad/minipot-server.hcl"
+if [ -n "$netif" ]; then
+	sysrc nomad_args="-config=/usr/local/etc/nomad/minipot-server.hcl -network-interface=$netif"
+else
+	sysrc nomad_args="-config=/usr/local/etc/nomad/minipot-server.hcl"
+fi
 sysrc consul_enable="YES"
 sysrc nomad_enable="YES"
 sysrc traefik_enable="YES"
